{
    "alarm_control_panel.py_o3_mini_e816d2fa.py": "temp_file.py:316: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:316: note: Left operand is of type \"Optional[datetime]\"\ntemp_file.py:420: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:420: note: Left operand is of type \"Optional[datetime]\"\ntemp_file.py:427: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:427: note: Left operand is of type \"Optional[datetime]\"\ntemp_file.py:431: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:431: note: Left operand is of type \"Optional[datetime]\"\nFound 4 errors in 1 file (checked 1 source file)\n",
    "inference.py_o3_mini_11291039.py": "temp_file.py:29: error: No parent module -- cannot perform relative import\ntemp_file.py:30: error: No parent module -- cannot perform relative import\ntemp_file.py:31: error: No parent module -- cannot perform relative import\ntemp_file.py:32: error: No parent module -- cannot perform relative import\nFound 4 errors in 1 file (errors prevented further checking)\n",
    "test_value_counts.py_o3_mini_32e737e2.py": "temp_file.py:97: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]\ntemp_file.py:322: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]\ntemp_file.py:1068: error: Argument 1 to \"list\" has incompatible type \"List[Optional[str]]\"; expected \"Iterable[str]\"  [arg-type]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "backtesting.py_o3_mini_86bf3a7e.py": "temp_file.py:1528: error: \"Backtesting\" has no attribute \"_time_pair_generator_det_det\"; maybe \"_time_pair_generator_det\", \"_time_generator_det\", or \"time_pair_generator\"?  [attr-defined]\ntemp_file.py:1599: error: Incompatible types in \"yield\" (actual type \"Tuple[Any, Any, Optional[Tuple[Any, ...]], bool, Optional[Any]]\", expected type \"Tuple[datetime, str, Tuple[Any, ...], bool, Optional[Any]]\")  [misc]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "embedding.py_o3_mini_64e6a5c5.py": "temp_file.py:156: error: Argument 4 to \"_read_pretrained_embeddings_file\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:311: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:314: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:432: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "trainer_test.py_o3_mini_cdc7ca6a.py": "temp_file.py:1421: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"LongTensor\")  [assignment]\ntemp_file.py:1433: error: Name \"torch.sparse.FloatTensor\" is not defined  [name-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "session.py_o3_mini_ce61005a.py": "temp_file.py:123: error: Invalid type comment or annotation  [valid-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "base_tests.py_o3_mini_525dc3b2.py": "temp_file.py:433: error: Argument \"json_\" to \"get_json_resp\" of \"SupersetTestCase\" has incompatible type \"Dict[str, Any]\"; expected \"Optional[str]\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "raiden_network.py_o3_mini_34be1bfe.py": "temp_file.py:210: error: Name \"pytest.MonkeyPatch\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_utils.py_o3_mini_ef0b5816.py": "temp_file.py:109: error: Value of type \"Optional[List[List[List[str]]]]\" is not indexable  [index]\ntemp_file.py:112: error: Value of type \"Optional[List[List[List[str]]]]\" is not indexable  [index]\ntemp_file.py:113: error: Argument 1 to \"len\" has incompatible type \"Optional[List[List[List[str]]]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:114: error: Value of type \"Optional[List[List[List[str]]]]\" is not indexable  [index]\ntemp_file.py:121: error: Item \"None\" of \"Optional[List[List[str]]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]\ntemp_file.py:127: error: Item \"None\" of \"Optional[List[List[List[str]]]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]\ntemp_file.py:133: error: Item \"None\" of \"Optional[List[List[str]]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]\ntemp_file.py:134: error: Item \"None\" of \"Optional[List[List[List[str]]]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]\nFound 8 errors in 1 file (checked 1 source file)\n",
    "__main__.py_o3_mini_9161fe52.py": "temp_file.py:12: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "network.py_o3_mini_8d1b1d1c.py": "temp_file.py:246: error: \"set\" is not subscriptable, use \"typing.Set\" instead  [misc]\ntemp_file.py:553: error: \"set\" is not subscriptable, use \"typing.Set\" instead  [misc]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "http_parser.py_o3_mini_b7839247.py": "temp_file.py:27: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "streams.py_o3_mini_4c29e46e.py": "temp_file.py:221: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]\nFound 1 error in 1 file (checked 1 source file)\n",
    "httpclient.py_o3_mini_76d1a39b.py": "temp_file.py:528: error: Unsupported target for indexed assignment (\"Union[Dict[str, str], Any, None]\")  [index]\nFound 1 error in 1 file (checked 1 source file)\n",
    "classification.py_o3_mini_554b95c0.py": "temp_file.py:223: error: Item \"List[Any]\" of \"Union[Any, List[Any]]\" has no attribute \"tolist\"  [union-attr]\ntemp_file.py:407: error: No overload variant of \"__getitem__\" of \"tuple\" matches argument type \"Tuple[slice, int]\"  [call-overload]\ntemp_file.py:407: note: Possible overload variants:\ntemp_file.py:407: note:     def __getitem__(self, SupportsIndex, /) -> Any\ntemp_file.py:407: note:     def __getitem__(self, slice, /) -> Tuple[Any, ...]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "base.py_o3_mini_41047fae.py": "temp_file.py:496: error: Incompatible types in assignment (expression has type \"MutableSequence[Any]\", variable has type \"List[Any]\")  [assignment]\ntemp_file.py:522: error: Cannot determine type of \"on_before_configured\"  [has-type]\ntemp_file.py:523: error: Cannot determine type of \"on_configured\"  [has-type]\ntemp_file.py:525: error: Cannot determine type of \"on_after_configured\"  [has-type]\ntemp_file.py:527: error: Cannot determine type of \"on_partitions_assigned\"  [has-type]\ntemp_file.py:529: error: Cannot determine type of \"on_partitions_revoked\"  [has-type]\ntemp_file.py:530: error: Cannot determine type of \"on_worker_init\"  [has-type]\ntemp_file.py:532: error: Cannot determine type of \"on_rebalance_complete\"  [has-type]\ntemp_file.py:534: error: Cannot determine type of \"on_before_shutdown\"  [has-type]\ntemp_file.py:536: error: Cannot determine type of \"on_produce_message\"  [has-type]\ntemp_file.py:659: error: Cannot determine type of \"finalized\"  [has-type]\ntemp_file.py:659: error: Cannot determine type of \"configured\"  [has-type]\ntemp_file.py:661: error: Cannot determine type of \"configured\"  [has-type]\ntemp_file.py:674: error: Cannot determine type of \"finalized\"  [has-type]\ntemp_file.py:1349: error: Function \"fun\" could always be true in boolean context  [truthy-function]\ntemp_file.py:1438: error: Name \"LiveCheck\" is not defined  [name-defined]\nFound 16 errors in 1 file (checked 1 source file)\n",
    "train_test.py_o3_mini_f735c70e.py": "temp_file.py:362: error: Name \"Archive\" is not defined  [name-defined]\ntemp_file.py:455: error: Name \"Archive\" is not defined  [name-defined]\ntemp_file.py:696: error: \"ExceptionInfo[SystemExit]\" has no attribute \"exception\"  [attr-defined]\ntemp_file.py:701: error: \"ExceptionInfo[SystemExit]\" has no attribute \"exception\"  [attr-defined]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "log.py_o3_mini_08a35b3f.py": "temp_file.py:294: error: Argument \"action\" to \"log_context\" of \"AbstractEventLogger\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "generic.py_o3_mini_4b81d00f.py": "temp_file.py:288: error: Argument 1 to \"_aggregate_multiple_funcs\" of \"SeriesGroupBy\" has incompatible type \"Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]], None]\"; expected \"Iterable[Union[Callable[..., Any], str]]\"  [arg-type]\ntemp_file.py:314: error: Argument 1 to \"_python_agg_general\" of \"SeriesGroupBy\" has incompatible type \"Optional[Callable[..., Any]]\"; expected \"Callable[..., Any]\"  [arg-type]\ntemp_file.py:341: error: Generator has incompatible item type \"Tuple[Union[Callable[..., Any], str], Union[Callable[..., Any], str]]\"; expected \"Union[Callable[..., Any], str]\"  [misc]\ntemp_file.py:345: error: Incompatible types in assignment (expression has type \"zip[Tuple[Union[Any, Callable[..., Any], str], Union[Callable[..., Any], str]]]\", variable has type \"Iterable[Union[Callable[..., Any], str]]\")  [assignment]\ntemp_file.py:351: error: \"Callable[..., Any]\" object is not iterable  [misc]\ntemp_file.py:351: error: Unpacking a string is disallowed  [misc]\ntemp_file.py:787: error: Name \"Tuple\" is not defined  [name-defined]\ntemp_file.py:787: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Tuple\")\ntemp_file.py:805: error: Name \"Tuple\" is not defined  [name-defined]\ntemp_file.py:805: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Tuple\")\ntemp_file.py:1117: error: Name \"Tuple\" is not defined  [name-defined]\ntemp_file.py:1117: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Tuple\")\ntemp_file.py:1308: error: Argument 1 to \"_python_agg_general\" of \"DataFrameGroupBy\" has incompatible type \"Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]], Dict[Any, Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]]]], None]\"; expected \"Callable[..., Any]\"  [arg-type]\ntemp_file.py:1312: error: Argument 1 to \"_aggregate_frame\" of \"DataFrameGroupBy\" has incompatible type \"Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]], Dict[Any, Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]]]], None]\"; expected \"Callable[..., Any]\"  [arg-type]\ntemp_file.py:1329: error: Argument 1 to \"_aggregate_frame\" of \"DataFrameGroupBy\" has incompatible type \"Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]], Dict[Any, Union[Callable[..., Any], str, List[Union[Callable[..., Any], str]]]], None]\"; expected \"Callable[..., Any]\"  [arg-type]\ntemp_file.py:1530: error: Name \"Tuple\" is not defined  [name-defined]\ntemp_file.py:1530: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Tuple\")\ntemp_file.py:1531: error: Name \"Tuple\" is not defined  [name-defined]\ntemp_file.py:1531: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Tuple\")\nFound 14 errors in 1 file (checked 1 source file)\n",
    "excel.py_o3_mini_a8ae7b91.py": "temp_file.py:222: error: Module has no attribute \"cache\"  [attr-defined]\ntemp_file.py:272: error: Argument 1 to \"remove_none\" has incompatible type \"Dict[str, Optional[Dict[str, Any]]]\"; expected \"Dict[str, Union[bool, str, float, None]]\"  [arg-type]\ntemp_file.py:393: error: Dict entry 0 has incompatible type \"str\": \"Optional[str]\"; expected \"str\": \"str\"  [dict-item]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "model_card.py_o3_mini_55460c7b.py": "temp_file.py:33: error: Item \"None\" of \"Optional[str]\" has no attribute \"split\"  [union-attr]\ntemp_file.py:582: error: Argument 1 to \"get_description\" has incompatible type \"Callable[..., Any]\"; expected \"type\"  [arg-type]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "mypy.py_o3_mini_6c8d5216.py": "temp_file.py:639: error: Argument 1 to \"error_extra_fields_on_root_model\" has incompatible type \"SemanticAnalyzerPluginInterface\"; expected \"CheckerPluginInterface\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "vocab.py_o3_mini_aa60a35d.py": "temp_file.py:64: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "testclient.py_o3_mini_b53c0624.py": "temp_file.py:98: error: Missing return statement  [return]\nFound 1 error in 1 file (checked 1 source file)\n",
    "matplotlib.py_o3_mini_714edf47.py": "temp_file.py:277: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:278: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:279: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:281: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:405: error: Cannot determine type of \"bottom\"  [has-type]\ntemp_file.py:406: error: Cannot determine type of \"bottom\"  [has-type]\ntemp_file.py:409: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:409: error: Cannot determine type of \"bins\"  [has-type]\ntemp_file.py:450: error: Argument 1 to \"len\" has incompatible type \"Optional[Any]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:452: error: Argument 1 to \"len\" has incompatible type \"Optional[Any]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:458: error: Value of type \"Optional[Any]\" is not indexable  [index]\ntemp_file.py:512: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:581: error: Name \"DataFrame\" is not defined  [name-defined]\ntemp_file.py:758: error: Name \"DataFrame\" is not defined  [name-defined]\ntemp_file.py:902: error: Argument \"subplots\" to \"_plot\" has incompatible type \"Optional[bool]\"; expected \"bool\"  [arg-type]\ntemp_file.py:927: error: Name \"DataFrame\" is not defined  [name-defined]\nFound 16 errors in 1 file (checked 1 source file)\n",
    "asserters.py_o3_mini_adee0207.py": "temp_file.py:249: error: Argument \"exact\" to \"assert_class_equal\" has incompatible type \"Union[Literal[True], str]\"; expected \"Union[bool, Literal['equiv']]\"  [arg-type]\ntemp_file.py:397: error: Missing positional argument \"right\" in call to \"raise_assert_detail\"  [call-arg]\ntemp_file.py:447: error: Value of type \"Union[Iterable[Any], Any, Any]\" is not indexable  [index]\ntemp_file.py:447: error: Item \"Iterable[Any]\" of \"Union[Iterable[Any], Any, Any]\" has no attribute \"argsort\"  [union-attr]\ntemp_file.py:1352: error: \"object\" has no attribute \"freq\"  [attr-defined]\nFound 5 errors in 1 file (checked 1 source file)\n",
    "multiprocess_data_loader.py_o3_mini_59f32091.py": "temp_file.py:379: error: Name \"mp.context.BaseContext\" is not defined  [name-defined]\ntemp_file.py:409: error: Name \"mp.context.BaseContext\" is not defined  [name-defined]\ntemp_file.py:440: error: Name \"mp.context.BaseContext\" is not defined  [name-defined]\ntemp_file.py:458: error: Name \"mp.context.BaseContext\" is not defined  [name-defined]\ntemp_file.py:540: error: Variable \"multiprocessing.RLock\" is not valid as a type  [valid-type]\ntemp_file.py:540: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:582: error: Variable \"multiprocessing.RLock\" is not valid as a type  [valid-type]\ntemp_file.py:582: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\nFound 6 errors in 1 file (checked 1 source file)\n",
    "_models.py_o3_mini_5798ddfd.py": "temp_file.py:365: error: \"Headers\" has no attribute \"multi_items\"  [attr-defined]\ntemp_file.py:1266: error: \"Headers\" has no attribute \"multi_items\"  [attr-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "response.py_o3_mini_c8730d4d.py": "temp_file.py:11: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:12: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:13: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:14: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:25: error: Function \"zlib.decompressobj\" is not valid as a type  [valid-type]\ntemp_file.py:25: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:35: error: zlib.decompressobj? has no attribute \"decompress\"  [attr-defined]\ntemp_file.py:40: error: zlib.decompressobj? has no attribute \"decompress\"  [attr-defined]\ntemp_file.py:59: error: Function \"zlib.decompressobj\" is not valid as a type  [valid-type]\ntemp_file.py:59: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:68: error: zlib.decompressobj? has no attribute \"decompress\"  [attr-defined]\ntemp_file.py:169: error: Missing return statement  [return]\nFound 10 errors in 1 file (checked 1 source file)\n",
    "awsclient.py_o3_mini_49cc8de2.py": "temp_file.py:1452: error: Incompatible types in \"yield\" (actual type \"Dict[str, Any]\", expected type \"CWLogEvent\")  [misc]\ntemp_file.py:1482: error: Incompatible return value type (got \"Dict[str, Any]\", expected \"LogEventsResponse\")  [return-value]\ntemp_file.py:1832: error: Incompatible types in assignment (expression has type \"Optional[int]\", variable has type \"int\")  [assignment]\ntemp_file.py:1859: error: Incompatible types in assignment (expression has type \"Optional[int]\", variable has type \"int\")  [assignment]\ntemp_file.py:2078: error: Argument 2 to \"isinstance\" has incompatible type \"Sequence[Exception]\"; expected \"_ClassInfo\"  [arg-type]\nFound 5 errors in 1 file (checked 1 source file)\n",
    "gymexperiments.py_o3_mini_116f21de.py": "temp_file.py:24: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:24: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\nFound 1 error in 1 file (checked 1 source file)\n",
    "missing.py_o3_mini_68837e1d.py": "temp_file.py:607: error: Incompatible types in assignment (expression has type \"str\", variable has type \"Optional[int]\")  [assignment]\ntemp_file.py:614: error: Unsupported operand types for >= (\"int\" and \"None\")  [operator]\ntemp_file.py:614: note: Left operand is of type \"Optional[int]\"\ntemp_file.py:865: error: Unexpected keyword argument \"limit\"  [call-arg]\ntemp_file.py:865: error: Unexpected keyword argument \"limit_area\"  [call-arg]\ntemp_file.py:1030: error: No overload variant of \"clean_fill_method\" matches argument type \"str\"  [call-overload]\ntemp_file.py:1030: note: Possible overload variants:\ntemp_file.py:1030: note:     def clean_fill_method(method: Literal['ffill', 'pad', 'bfill', 'backfill'], *, allow_nearest: Literal[False] = ...) -> Literal['pad', 'backfill']\ntemp_file.py:1030: note:     def clean_fill_method(method: Literal['ffill', 'pad', 'bfill', 'backfill', 'nearest'], *, allow_nearest: Literal[True]) -> Literal['pad', 'backfill', 'nearest']\ntemp_file.py:1039: error: No overload variant of \"clean_fill_method\" matches argument types \"str\", \"bool\"  [call-overload]\ntemp_file.py:1039: note: Possible overload variants:\ntemp_file.py:1039: note:     def clean_fill_method(method: Literal['ffill', 'pad', 'bfill', 'backfill'], *, allow_nearest: Literal[False] = ...) -> Literal['pad', 'backfill']\ntemp_file.py:1039: note:     def clean_fill_method(method: Literal['ffill', 'pad', 'bfill', 'backfill', 'nearest'], *, allow_nearest: Literal[True]) -> Literal['pad', 'backfill', 'nearest']\nFound 6 errors in 1 file (checked 1 source file)\n",
    "test_appgraph.py_o3_mini_d2cf8562.py": "temp_file.py:246: error: Missing return statement  [empty-body]\nFound 1 error in 1 file (checked 1 source file)\n",
    "html.py_o3_mini_1065c3b5.py": "temp_file.py:646: error: Item \"str\" of \"Union[str, Pattern[Any]]\" has no attribute \"pattern\"  [union-attr]\ntemp_file.py:757: error: Item \"str\" of \"Union[str, Pattern[Any]]\" has no attribute \"pattern\"  [union-attr]\ntemp_file.py:1008: error: \"str\" has no attribute \"seek\"  [attr-defined]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "notify.py_o3_mini_79a4d062.py": "temp_file.py:152: error: Incompatible types in assignment (expression has type \"SMTP\", variable has type \"SMTP_SSL\")  [assignment]\ntemp_file.py:167: error: Module \"smtplib\" does not explicitly export attribute \"socket\"  [attr-defined]\ntemp_file.py:210: error: Incompatible types in assignment (expression has type \"MIMEText\", variable has type \"MIMEMultipart\")  [assignment]\ntemp_file.py:291: error: Incompatible types in assignment (expression has type \"MIMEApplication\", variable has type \"MIMEImage\")  [assignment]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "validator.py_o3_mini_af420d1c.py": "temp_file.py:200: error: Incompatible return value type (got \"Tuple[zip[Tuple[Any, Any]], List[Any]]\", expected \"Tuple[Tuple[Any, Any], List[Any]]\")  [return-value]\nFound 1 error in 1 file (checked 1 source file)\n",
    "t5.py_o3_mini_d3f65209.py": "temp_file.py:430: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:431: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:433: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:491: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[IntTensor]\")  [assignment]\ntemp_file.py:520: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:525: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:548: error: List item 0 has incompatible type \"None\"; expected \"Union[Tuple[Any, Any], Tuple[Any, Any, Any, Any]]\"  [list-item]\ntemp_file.py:937: error: Argument 1 to \"T5LayerNorm\" has incompatible type \"**Dict[str, Union[int, float]]\"; expected \"int\"  [arg-type]\ntemp_file.py:948: error: Argument 1 to \"T5LayerNorm\" has incompatible type \"**Dict[str, Union[int, float]]\"; expected \"int\"  [arg-type]\ntemp_file.py:964: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"IntTensor\")  [assignment]\ntemp_file.py:993: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:1013: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:1045: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"IntTensor\")  [assignment]\ntemp_file.py:1054: error: Dict entry 2 has incompatible type \"str\": \"Optional[BoolTensor]\"; expected \"str\": \"Tensor\"  [dict-item]\nFound 14 errors in 1 file (checked 1 source file)\n",
    "message.py_o3_mini_497b1e8f.py": "temp_file.py:83: error: Name \"validate_is_bytes\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "schema_generic_tests.py_o3_mini_d32963a8.py": "temp_file.py:120: error: List item 1 has incompatible type \"Union[str, List[Any], Dict[str, Any]]\"; expected \"str\"  [list-item]\nFound 1 error in 1 file (checked 1 source file)\n",
    "training.py_o3_mini_79729440.py": "temp_file.py:40: error: No parent module -- cannot perform relative import\ntemp_file.py:41: error: No parent module -- cannot perform relative import\ntemp_file.py:42: error: No parent module -- cannot perform relative import\ntemp_file.py:43: error: No parent module -- cannot perform relative import\ntemp_file.py:44: error: No parent module -- cannot perform relative import\ntemp_file.py:45: error: No parent module -- cannot perform relative import\ntemp_file.py:46: error: No parent module -- cannot perform relative import\ntemp_file.py:47: error: No parent module -- cannot perform relative import\ntemp_file.py:48: error: No parent module -- cannot perform relative import\ntemp_file.py:49: error: No parent module -- cannot perform relative import\nFound 10 errors in 1 file (errors prevented further checking)\n",
    "sensor.py_o3_mini_85e008f1.py": "temp_file.py:64: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "_misc.py_o3_mini_e437bff3.py": "temp_file.py:738: error: Argument 1 of \"__contains__\" is incompatible with supertype \"Mapping\"; supertype defines the argument type as \"object\"  [override]\ntemp_file.py:738: note: This violates the Liskov substitution principle\ntemp_file.py:738: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides\ntemp_file.py:738: error: Argument 1 of \"__contains__\" is incompatible with supertype \"Container\"; supertype defines the argument type as \"object\"  [override]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "mocks.py_o3_mini_852f4d73.py": "temp_file.py:208: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:208: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:209: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:209: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:266: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:266: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:274: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:274: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:278: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:278: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:281: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:281: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:284: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:284: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:330: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:330: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:342: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:342: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:366: error: Variable \"temp_file.RoutesDict\" is not valid as a type  [valid-type]\ntemp_file.py:366: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:437: error: Value of type RoutesDict? is not indexable  [index]\ntemp_file.py:441: error: RoutesDict? has no attribute \"clear\"  [attr-defined]\ntemp_file.py:443: error: Value of type RoutesDict? is not indexable  [index]\ntemp_file.py:457: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:457: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:465: error: Value of type RoutesDict? is not indexable  [index]\nFound 15 errors in 1 file (checked 1 source file)\n",
    "pretrained_transformer_embedder.py_o3_mini_193bb568.py": "temp_file.py:227: error: Argument 2 to \"_fold_long_sequences\" of \"PretrainedTransformerEmbedder\" has incompatible type \"Optional[BoolTensor]\"; expected \"BoolTensor\"  [arg-type]\ntemp_file.py:230: error: Incompatible types in assignment (expression has type \"Optional[BoolTensor]\", variable has type \"BoolTensor\")  [assignment]\ntemp_file.py:254: error: Argument 1 to \"_unfold_long_sequences\" of \"PretrainedTransformerEmbedder\" has incompatible type \"Tensor\"; expected \"FloatTensor\"  [arg-type]\ntemp_file.py:254: error: Argument 2 to \"_unfold_long_sequences\" of \"PretrainedTransformerEmbedder\" has incompatible type \"Optional[BoolTensor]\"; expected \"BoolTensor\"  [arg-type]\ntemp_file.py:300: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"LongTensor\")  [assignment]\ntemp_file.py:302: error: Incompatible return value type (got \"Tensor\", expected \"LongTensor\")  [return-value]\ntemp_file.py:302: error: Argument 2 to \"reshape\" of \"TensorBase\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]\ntemp_file.py:305: error: Incompatible types in assignment (expression has type \"LongTensor\", variable has type \"BoolTensor\")  [assignment]\ntemp_file.py:305: error: Argument 1 to \"fold\" has incompatible type \"BoolTensor\"; expected \"LongTensor\"  [arg-type]\ntemp_file.py:347: error: Incompatible return value type (got \"Tensor\", expected \"BoolTensor\")  [return-value]\ntemp_file.py:372: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"LongTensor\")  [assignment]\ntemp_file.py:376: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:380: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:380: error: Argument 3 to \"reshape\" of \"TensorBase\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]\ntemp_file.py:381: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:384: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:396: error: Result type of - incompatible in assignment  [misc]\ntemp_file.py:399: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:407: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:410: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\nFound 20 errors in 1 file (checked 1 source file)\n",
    "BaseEnvironment.py_o3_mini_5f8d69fa.py": "temp_file.py:91: error: \"type\" expects no type arguments, but 1 given  [type-arg]\ntemp_file.py:142: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:142: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:144: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:144: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:144: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:151: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:151: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:166: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:167: error: \"type\" has no attribute \"__iter__\" (not iterable)  [attr-defined]\ntemp_file.py:169: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:176: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:176: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:177: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:177: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:213: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:213: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:213: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:240: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:240: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:241: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:247: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:379: error: \"type\" expects no type arguments, but 1 given  [type-arg]\nFound 17 errors in 1 file (checked 1 source file)\n",
    "transactions.py_o3_mini_8abeba06.py": "temp_file.py:81: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:98: error: Incompatible default for argument \"chain_id\" (default has type \"None\", argument has type \"int\")  [assignment]\ntemp_file.py:98: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:98: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\ntemp_file.py:142: error: Incompatible default for argument \"chain_id\" (default has type \"None\", argument has type \"int\")  [assignment]\ntemp_file.py:142: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:142: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\nFound 3 errors in 1 file (checked 1 source file)\n",
    "format.py_o3_mini_80a9d557.py": "temp_file.py:1034: error: \"Generator\" expects 3 type arguments, but 1 given  [type-arg]\ntemp_file.py:1594: error: Incompatible return value type (got \"Union[str, float]\", expected \"str\")  [return-value]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "_main.py_o3_mini_93f26c03.py": "temp_file.py:249: error: Too many values to unpack (2 expected, 4 provided)  [misc]\ntemp_file.py:306: error: Incompatible return value type (got \"Tuple[Optional[str], Optional[str]]\", expected \"Optional[Tuple[str, str]]\")  [return-value]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "test_interface.py_o3_mini_c697fae0.py": "temp_file.py:128: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:128: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:138: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:138: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:155: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:155: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:170: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:170: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:189: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:189: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:233: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:233: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:251: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:251: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:310: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:310: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:326: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:326: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:337: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:337: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:364: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:364: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:398: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:398: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:547: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:547: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:551: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:551: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:557: error: Name \"Optional\" is not defined  [name-defined]\ntemp_file.py:557: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Optional\")\ntemp_file.py:557: error: Name \"Callable\" is not defined  [name-defined]\ntemp_file.py:557: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Callable\")\ntemp_file.py:619: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:619: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:660: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:660: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:761: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:761: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:792: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:792: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:1024: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:1024: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:1077: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:1077: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\ntemp_file.py:1092: error: Name \"Any\" is not defined  [name-defined]\ntemp_file.py:1092: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Any\")\nFound 23 errors in 1 file (checked 1 source file)\n",
    "modern.py_o3_mini_e73854b5.py": "temp_file.py:30: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:31: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:37: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:38: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:44: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:769: error: Argument 5 has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "weather.py_o3_mini_80b5c19e.py": "temp_file.py:238: error: Function \"datetime.datetime.date\" is not valid as a type  [valid-type]\ntemp_file.py:238: note: Perhaps you need \"Callable[...]\" or a callback protocol?\nFound 1 error in 1 file (checked 1 source file)\n",
    "concat.py_o3_mini_b116fbaa.py": "temp_file.py:588: error: Unexpected \"...\"  [misc]\ntemp_file.py:588: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:756: error: Invalid index type \"Union[Any, Hashable]\" for \"Union[Mapping[Any, Any], Mapping[HashableT_co, Any]]\"; expected type \"HashableT_co\"  [index]\ntemp_file.py:771: error: Argument 1 to \"len\" has incompatible type \"Union[Iterable[Hashable], Any, None]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:774: error: Argument 1 to \"len\" has incompatible type \"Union[Iterable[Hashable], Any, None]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:796: error: Argument 1 to \"len\" has incompatible type \"Union[Iterable[Hashable], Any]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:797: error: Item \"Iterable[Hashable]\" of \"Union[Iterable[Hashable], Any]\" has no attribute \"take\"  [union-attr]\ntemp_file.py:854: error: No overload variant of \"zip\" matches argument type \"Iterable[Hashable]\"  [call-overload]\ntemp_file.py:854: note: Possible overload variants:\ntemp_file.py:854: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:854: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:854: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:854: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:854: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:854: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\ntemp_file.py:856: error: List item 0 has incompatible type \"None\"; expected \"HashableT_co\"  [list-item]\ntemp_file.py:866: error: List item 0 has incompatible type \"None\"; expected \"HashableT_co\"  [list-item]\nFound 10 errors in 1 file (checked 1 source file)\n",
    "channel.py_o3_mini_d20e5ead.py": "temp_file.py:2324: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"List[Any]\")  [assignment]\ntemp_file.py:2332: error: Name \"pending_locks\" is not defined  [name-defined]\ntemp_file.py:2335: error: Name \"pending_locks\" is not defined  [name-defined]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "conftest.py_o3_mini_ef4e97b9.py": "temp_file.py:49: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "test_planner.py_o3_mini_8f4efc62.py": "temp_file.py:215: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:236: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:263: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:330: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:372: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:497: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:558: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:597: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:636: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:731: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:794: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:1485: error: Item \"None\" of \"Optional[Any]\" has no attribute \"messages\"  [union-attr]\ntemp_file.py:2600: error: Need type annotation for \"deployed_resources\"  [var-annotated]\ntemp_file.py:2653: error: Need type annotation for \"deployed_resources\"  [var-annotated]\ntemp_file.py:2719: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2728: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2779: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2795: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2837: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2852: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2870: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2900: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2918: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:2993: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3084: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3139: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3251: error: \"TestUnreferencedResourcePlanner\" has no attribute \"one_deployed_lambda_function\"  [attr-defined]\ntemp_file.py:3253: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3258: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3259: error: \"TestUnreferencedResourcePlanner\" has no attribute \"one_deployed_lambda_function\"  [attr-defined]\ntemp_file.py:3261: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3267: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3276: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3312: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3318: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3328: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3334: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3361: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3376: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3383: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3391: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3400: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3409: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3419: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3439: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3448: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3457: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3466: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3494: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3528: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3532: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3544: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3582: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3620: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3624: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3635: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3663: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3679: error: Need type annotation for \"plan\" (hint: \"plan: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:3681: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3713: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3743: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3744: error: \"TestUnreferencedResourcePlanner\" has no attribute \"sweeper\"  [attr-defined]\ntemp_file.py:3772: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3773: error: \"TestUnreferencedResourcePlanner\" has no attribute \"sweeper\"  [attr-defined]\ntemp_file.py:3789: error: \"TestUnreferencedResourcePlanner\" has no attribute \"execute\"  [attr-defined]\ntemp_file.py:3792: error: Incompatible types in assignment (expression has type \"Tuple[Any, Any]\", variable has type \"Tuple[Any]\")  [assignment]\ntemp_file.py:3805: error: \"TestUnreferencedResourcePlanner\" has no attribute \"sweeper\"  [attr-defined]\ntemp_file.py:3806: error: \"TestUnreferencedResourcePlanner\" has no attribute \"sweeper\"  [attr-defined]\nFound 68 errors in 1 file (checked 1 source file)\n"
}