{
    "accessor_9a03f0.py": {
        "stats": {
            "total_parameters": 38,
            "parameters_with_annotations": 32
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "accessor_9a03f0.py:132: error: Incompatible types in assignment (expression has type \"range\", variable has type \"Optional[str]\")  [assignment]",
            "accessor_9a03f0.py:134: error: Argument 1 to \"zip\" has incompatible type \"Optional[str]\"; expected \"Iterable[str]\"  [arg-type]",
            "accessor_9a03f0.py:211: error: Need type annotation for \"los\" (hint: \"los: List[<type>] = ...\")  [var-annotated]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "api_tests_b98962.py": {
        "stats": {
            "total_parameters": 29,
            "parameters_with_annotations": 6
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "api_test_5baf5c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "api_test_5baf5c.py:366: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "appgraph_e5732d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "appgraph_e5732d.py:323: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "app_9acae6.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "app_9acae6.py:181: error: closing parenthesis ']' does not match opening parenthesis '('  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "array_1d8ad4.py": {
        "stats": {
            "total_parameters": 25,
            "parameters_with_annotations": 17
        },
        "error_count": 7,
        "isCompiled": false,
        "errors": [
            "array_1d8ad4.py:81: error: Variable \"builtins.NotImplemented\" is not valid as a type  [valid-type]",
            "array_1d8ad4.py:81: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases",
            "array_1d8ad4.py:178: error: \"Sequence[str]\" has no attribute \"cast\"  [attr-defined]",
            "array_1d8ad4.py:191: error: \"Sequence[str]\" has no attribute \"cast\"  [attr-defined]",
            "array_1d8ad4.py:247: error: \"Sequence[Any]\" has no attribute \"copy\"  [attr-defined]",
            "array_1d8ad4.py:254: error: \"Sequence[Any]\" has no attribute \"to_numpy\"  [attr-defined]",
            "array_1d8ad4.py:262: error: \"Sequence[Any]\" has no attribute \"to_numpy\"  [attr-defined]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "asserters_700def.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "asserters_700def.py:348: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "attestations_9893da.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "attestations_9893da.py:261: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "awsclient_860c67.py": {
        "stats": {
            "total_parameters": 100,
            "parameters_with_annotations": 68
        },
        "error_count": 27,
        "isCompiled": false,
        "errors": [
            "awsclient_860c67.py:160: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:168: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:179: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:195: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:203: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:207: error: Need type annotation for \"vpc_config\"  [var-annotated]",
            "awsclient_860c67.py:215: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:219: error: \"TypedAWSClient\" has no attribute \"_get_lambda_code_deployment_error\"  [attr-defined]",
            "awsclient_860c67.py:222: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:230: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:252: error: Incompatible types in assignment (expression has type \"int\", target has type \"Collection[str]\")  [assignment]",
            "awsclient_860c67.py:254: error: Incompatible types in assignment (expression has type \"int\", target has type \"Collection[str]\")  [assignment]",
            "awsclient_860c67.py:265: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:278: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:287: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:310: error: \"TypedAWSClient\" has no attribute \"get_custom_domain_params_v2\"  [attr-defined]",
            "awsclient_860c67.py:319: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:321: error: \"TypedAWSClient\" has no attribute \"_call_client_method_with_retries\"  [attr-defined]",
            "awsclient_860c67.py:340: error: Incompatible return value type (got \"Dict[str, Any]\", expected \"DomainNameResponse\")  [return-value]",
            "awsclient_860c67.py:343: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:345: error: \"TypedAWSClient\" has no attribute \"_call_client_method_with_retries\"  [attr-defined]",
            "awsclient_860c67.py:353: error: Incompatible return value type (got \"Dict[str, Any]\", expected \"DomainNameResponse\")  [return-value]",
            "awsclient_860c67.py:357: error: \"TypedAWSClient\" has no attribute \"_call_client_method_with_retries\"  [attr-defined]",
            "awsclient_860c67.py:357: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:363: error: \"TypedAWSClient\" has no attribute \"_get_lambda_code_deployment_error\"  [attr-defined]",
            "awsclient_860c67.py:374: error: Incompatible types in assignment (expression has type \"bytes\", target has type \"str\")  [assignment]",
            "awsclient_860c67.py:376: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "Found 27 errors in 1 file (checked 1 source file)"
        ]
    },
    "backtesting_a4b109.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "backtesting_a4b109.py:296: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "base_73fb43.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "base_73fb43.py:369: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "base_bb93b4.py": {
        "stats": {
            "total_parameters": 128,
            "parameters_with_annotations": 77
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "base_bb93b4.py:29: error: \"BaseStringArrayMethods\" has no attribute \"_str_slice\"  [attr-defined]",
            "base_bb93b4.py:31: error: \"BaseStringArrayMethods\" has no attribute \"_str_get\"  [attr-defined]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "base_tests_a1e90e.py": {
        "stats": {
            "total_parameters": 92,
            "parameters_with_annotations": 72
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "base_tests_a1e90e.py:91: error: \"Type[T]\" has no attribute \"id\"  [attr-defined]",
            "base_tests_a1e90e.py:209: error: Name \"func_irddn4kj\" is not defined  [name-defined]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "clienttrader_5e3b99.py": {
        "stats": {
            "total_parameters": 86,
            "parameters_with_annotations": 39
        },
        "error_count": 82,
        "isCompiled": false,
        "errors": [
            "clienttrader_5e3b99.py:81: error: \"ClientTrader\" has no attribute \"broker_type\"  [attr-defined]",
            "clienttrader_5e3b99.py:110: error: \"ClientTrader\" has no attribute \"_close_prompt_windows\"  [attr-defined]",
            "clienttrader_5e3b99.py:112: error: \"ClientTrader\" has no attribute \"_init_toolbar\"; maybe \"_toolbar\"?  [attr-defined]",
            "clienttrader_5e3b99.py:120: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:121: error: \"ClientTrader\" has no attribute \"_get_balance_from_statics\"  [attr-defined]",
            "clienttrader_5e3b99.py:124: error: Item \"None\" of \"Optional[Any]\" has no attribute \"child_window\"  [union-attr]",
            "clienttrader_5e3b99.py:129: error: Item \"None\" of \"Optional[Any]\" has no attribute \"child_window\"  [union-attr]",
            "clienttrader_5e3b99.py:135: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:136: error: \"ClientTrader\" has no attribute \"_get_grid_data\"  [attr-defined]",
            "clienttrader_5e3b99.py:140: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:141: error: \"ClientTrader\" has no attribute \"_get_grid_data\"  [attr-defined]",
            "clienttrader_5e3b99.py:145: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:146: error: \"ClientTrader\" has no attribute \"_get_grid_data\"  [attr-defined]",
            "clienttrader_5e3b99.py:150: error: \"ClientTrader\" has no attribute \"refresh\"  [attr-defined]",
            "clienttrader_5e3b99.py:151: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:152: error: \"ClientTrader\" has no attribute \"_get_grid_data\"  [attr-defined]",
            "clienttrader_5e3b99.py:156: error: \"ClientTrader\" has no attribute \"refresh\"  [attr-defined]",
            "clienttrader_5e3b99.py:157: error: \"ClientTrader\" has no attribute \"cancel_entrusts\"  [attr-defined]",
            "clienttrader_5e3b99.py:160: error: \"ClientTrader\" has no attribute \"_cancel_entrust_by_double_click\"  [attr-defined]",
            "clienttrader_5e3b99.py:161: error: \"ClientTrader\" has no attribute \"_handle_pop_dialogs\"  [attr-defined]",
            "clienttrader_5e3b99.py:165: error: \"ClientTrader\" has no attribute \"refresh\"  [attr-defined]",
            "clienttrader_5e3b99.py:166: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:167: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:170: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:171: error: \"ClientTrader\" has no attribute \"is_exist_pop_dialog\"  [attr-defined]",
            "clienttrader_5e3b99.py:172: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:177: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:178: error: \"ClientTrader\" has no attribute \"close_pop_dialog\"  [attr-defined]",
            "clienttrader_5e3b99.py:182: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:183: error: \"ClientTrader\" has no attribute \"trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:187: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:188: error: \"ClientTrader\" has no attribute \"trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:192: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:193: error: \"ClientTrader\" has no attribute \"trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:197: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:198: error: \"ClientTrader\" has no attribute \"trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:214: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:215: error: \"ClientTrader\" has no attribute \"market_trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:231: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:232: error: \"ClientTrader\" has no attribute \"market_trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:248: error: \"ClientTrader\" has no attribute \"_type_edit_control_keys\"  [attr-defined]",
            "clienttrader_5e3b99.py:255: error: \"ClientTrader\" has no attribute \"_set_market_trade_type\"  [attr-defined]",
            "clienttrader_5e3b99.py:259: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:260: error: \"ClientTrader\" has no attribute \"_set_market_trade_params\"  [attr-defined]",
            "clienttrader_5e3b99.py:262: error: \"ClientTrader\" has no attribute \"_submit_trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:263: error: \"ClientTrader\" has no attribute \"_handle_pop_dialogs\"  [attr-defined]",
            "clienttrader_5e3b99.py:268: error: Item \"None\" of \"Optional[Any]\" has no attribute \"child_window\"  [union-attr]",
            "clienttrader_5e3b99.py:283: error: Item \"None\" of \"Optional[Any]\" has no attribute \"child_window\"  [union-attr]",
            "clienttrader_5e3b99.py:297: error: \"ClientTrader\" has no attribute \"_switch_left_menus\"  [attr-defined]",
            "clienttrader_5e3b99.py:298: error: \"ClientTrader\" has no attribute \"_get_grid_data\"  [attr-defined]",
            "clienttrader_5e3b99.py:301: error: \"ClientTrader\" has no attribute \"config\"; maybe \"_config\"?  [attr-defined]",
            "clienttrader_5e3b99.py:305: error: \"ClientTrader\" has no attribute \"_click\"  [attr-defined]",
            "clienttrader_5e3b99.py:306: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:308: error: \"ClientTrader\" has no attribute \"_click_grid_by_row\"  [attr-defined]",
            "clienttrader_5e3b99.py:309: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:310: error: \"ClientTrader\" has no attribute \"_click\"  [attr-defined]",
            "clienttrader_5e3b99.py:311: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:312: error: \"ClientTrader\" has no attribute \"_handle_pop_dialogs\"  [attr-defined]",
            "clienttrader_5e3b99.py:318: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:324: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:326: error: Item \"None\" of \"Optional[Any]\" has no attribute \"wrapper_object\"  [union-attr]",
            "clienttrader_5e3b99.py:326: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:336: error: Item \"None\" of \"Optional[Any]\" has no attribute \"wrapper_object\"  [union-attr]",
            "clienttrader_5e3b99.py:336: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:338: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:341: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:353: error: Item \"None\" of \"Optional[Any]\" has no attribute \"kill\"  [union-attr]",
            "clienttrader_5e3b99.py:356: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:357: error: Item \"None\" of \"Optional[Any]\" has no attribute \"windows\"  [union-attr]",
            "clienttrader_5e3b99.py:363: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:364: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:367: error: Item \"None\" of \"Optional[Any]\" has no attribute \"windows\"  [union-attr]",
            "clienttrader_5e3b99.py:372: error: \"ClientTrader\" has no attribute \"_set_trade_params\"  [attr-defined]",
            "clienttrader_5e3b99.py:373: error: \"ClientTrader\" has no attribute \"_submit_trade\"  [attr-defined]",
            "clienttrader_5e3b99.py:374: error: \"ClientTrader\" has no attribute \"_handle_pop_dialogs\"  [attr-defined]",
            "clienttrader_5e3b99.py:378: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:384: error: Item \"None\" of \"Optional[Any]\" has no attribute \"child_window\"  [union-attr]",
            "clienttrader_5e3b99.py:389: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:394: error: Item \"None\" of \"Optional[Any]\" has no attribute \"top_window\"  [union-attr]",
            "clienttrader_5e3b99.py:399: error: \"ClientTrader\" has no attribute \"_type_edit_control_keys\"  [attr-defined]",
            "clienttrader_5e3b99.py:401: error: \"ClientTrader\" has no attribute \"wait\"  [attr-defined]",
            "clienttrader_5e3b99.py:403: error: \"ClientTrader\" has no attribute \"_set_stock_exchange\"  [attr-defined]",
            "Found 82 errors in 1 file (checked 1 source file)"
        ]
    },
    "color_a02da4.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "color_a02da4.py:223: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "commands_tests_eb6597.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "commands_tests_eb6597.py:396: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "conftest_51a703.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "conftest_51a703.py:284: error: Name \"load_json\" is not defined  [name-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "controllers_c0fa43.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "controllers_c0fa43.py:434: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "converter_d3febb.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "converter_d3febb.py:377: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "core_c55873.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "core_c55873.py:385: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "database_5bbb39.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "database_5bbb39.py:454: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "datastructures_0a7b11.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "datastructures_0a7b11.py:474: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "data_0433fa.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "data_0433fa.py:48: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "data_kitchen_58b770.py": {
        "stats": {
            "total_parameters": 50,
            "parameters_with_annotations": 34
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "data_kitchen_58b770.py:46: error: \"FreqaiDataKitchen\" has no attribute \"set_all_pairs\"; maybe \"all_pairs\"?  [attr-defined]",
            "data_kitchen_58b770.py:52: error: \"FreqaiDataKitchen\" has no attribute \"get_full_models_path\"  [attr-defined]",
            "data_kitchen_58b770.py:72: error: \"FreqaiDataKitchen\" has no attribute \"get_full_models_path\"  [attr-defined]",
            "data_kitchen_58b770.py:265: error: Missing return statement  [return]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "datetimelike_f48bd1.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "datetimelike_f48bd1.py:432: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "datetimes_71dd39.py": {
        "stats": {
            "total_parameters": 56,
            "parameters_with_annotations": 36
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "datetimes_71dd39.py:37: error: Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader  [misc]",
            "datetimes_71dd39.py:98: error: Name \"_validate_dt64_dtype\" is not defined  [name-defined]",
            "datetimes_71dd39.py:99: error: Name \"_validate_dt64_dtype\" is not defined  [name-defined]",
            "datetimes_71dd39.py:133: error: Name \"_validate_dt64_dtype\" is not defined  [name-defined]",
            "datetimes_71dd39.py:134: error: Name \"_validate_tz_from_dtype\" is not defined  [name-defined]",
            "datetimes_71dd39.py:142: error: Name \"_sequence_to_dt64\" is not defined  [name-defined]",
            "datetimes_71dd39.py:143: error: Name \"_validate_tz_from_dtype\" is not defined  [name-defined]",
            "datetimes_71dd39.py:179: error: Name \"_maybe_normalize_endpoints\" is not defined  [name-defined]",
            "datetimes_71dd39.py:180: error: Name \"_infer_tz_from_endpoints\" is not defined  [name-defined]",
            "datetimes_71dd39.py:182: error: Name \"_maybe_localize_point\" is not defined  [name-defined]",
            "datetimes_71dd39.py:183: error: Name \"_maybe_localize_point\" is not defined  [name-defined]",
            "datetimes_71dd39.py:193: error: Name \"func_qszdfm6v\" is not defined  [name-defined]",
            "datetimes_71dd39.py:306: error: Name \"ast\" is not defined  [name-defined]",
            "Found 13 errors in 1 file (checked 1 source file)"
        ]
    },
    "excel_26f18f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "excel_26f18f.py:433: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "exceptions_34f7ac.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "exceptions_34f7ac.py:344: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "export_6707ca.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "export_6707ca.py:327: error: EOF while scanning triple-quoted string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "expr_a7337f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "expr_a7337f.py:376: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fork_choice_4f67df.py": {
        "stats": {
            "total_parameters": 113,
            "parameters_with_annotations": 113
        },
        "error_count": 9,
        "isCompiled": false,
        "errors": [
            "fork_choice_4f67df.py:53: error: Name \"on_tick_and_append_step\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:54: error: Name \"add_block\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:67: error: Name \"get_attestation_file_name\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:68: error: Name \"get_attestation_file_name\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:94: error: Name \"get_genesis_forkchoice_store_and_block\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:121: error: Name \"output_store_checks\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:150: error: Item \"None\" of \"Optional[BlobData]\" has no attribute \"proofs\"  [union-attr]",
            "fork_choice_4f67df.py:175: error: Name \"run_on_attester_slashing\" is not defined  [name-defined]",
            "fork_choice_4f67df.py:180: error: Name \"output_store_checks\" is not defined  [name-defined]",
            "Found 9 errors in 1 file (checked 1 source file)"
        ]
    },
    "format_84da8c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "format_84da8c.py:111: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "freqai_interface_c93cd2.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "freqai_interface_c93cd2.py:244: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "freqtradebot_43234d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "freqtradebot_43234d.py:328: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "generic_a07530.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "generic_a07530.py:75: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "hist_13f59f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "hist_13f59f.py:298: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "html_2728b0.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "html_2728b0.py:292: error: unmatched ']'  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "idatahandler_cafafa.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "idatahandler_cafafa.py:342: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "import_realm_55d1ca.py": {
        "stats": {
            "total_parameters": 50,
            "parameters_with_annotations": 50
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "import_realm_55d1ca.py:124: error: Name \"get_db_table\" is not defined  [name-defined]",
            "import_realm_55d1ca.py:175: error: Name \"re_map_foreign_keys_many_to_many_internal\" is not defined  [name-defined]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "indexing_d02a25.py": {
        "stats": {
            "total_parameters": 71,
            "parameters_with_annotations": 39
        },
        "error_count": 17,
        "isCompiled": false,
        "errors": [
            "indexing_d02a25.py:57: error: Name \"_iLocIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:58: error: Name \"_iLocIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:65: error: Name \"_AtIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:66: error: Name \"_AtIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:69: error: Name \"_iAtIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:70: error: Name \"_iAtIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:90: error: Name \"check_dict_or_set_indexers\" is not defined  [name-defined]",
            "indexing_d02a25.py:92: error: Name \"_tupleize_axis_indexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:156: error: Name \"check_dict_or_set_indexers\" is not defined  [name-defined]",
            "indexing_d02a25.py:165: error: Name \"_iLocIndexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:166: error: Name \"func_nnm8v7yr\" is not defined  [name-defined]",
            "indexing_d02a25.py:198: error: Name \"is_nested_tuple\" is not defined  [name-defined]",
            "indexing_d02a25.py:245: error: Name \"is_label_like\" is not defined  [name-defined]",
            "indexing_d02a25.py:267: error: Name \"check_dict_or_set_indexers\" is not defined  [name-defined]",
            "indexing_d02a25.py:300: error: Name \"check_dict_or_set_indexers\" is not defined  [name-defined]",
            "indexing_d02a25.py:328: error: Name \"check_bool_indexer\" is not defined  [name-defined]",
            "indexing_d02a25.py:332: error: \"Type[IndexingMixin]\" has no attribute \"loc\"  [attr-defined]",
            "Found 17 errors in 1 file (checked 1 source file)"
        ]
    },
    "info_58f159.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "info_58f159.py:228: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "interface_c3b648.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "interface_c3b648.py:376: error: EOF while scanning triple-quoted string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "linegen_ea8858.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 14
        },
        "error_count": 8,
        "isCompiled": false,
        "errors": [
            "linegen_ea8858.py:42: error: Cannot determine type of \"current_line\"  [has-type]",
            "linegen_ea8858.py:43: error: Cannot determine type of \"current_line\"  [has-type]",
            "linegen_ea8858.py:45: error: Cannot determine type of \"current_line\"  [has-type]",
            "linegen_ea8858.py:47: error: Cannot determine type of \"current_line\"  [has-type]",
            "linegen_ea8858.py:77: error: Need type annotation for \"\u00d8\" (hint: \"\u00d8: Set[<type>] = ...\")  [var-annotated]",
            "linegen_ea8858.py:116: error: Need type annotation for \"result\" (hint: \"result: List[<type>] = ...\")  [var-annotated]",
            "linegen_ea8858.py:124: error: Name \"func_sw1drj12\" is not defined  [name-defined]",
            "linegen_ea8858.py:128: error: Name \"func_sw1drj12\" is not defined  [name-defined]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "manifest_47c52e.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "manifest_47c52e.py:364: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "manifest_87d3d1.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "manifest_87d3d1.py:318: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "mattermost_5a1f15.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "mattermost_5a1f15.py:186: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "mediator_edd547.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "mediator_edd547.py:138: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "merge_f40757.py": {
        "stats": {
            "total_parameters": 191,
            "parameters_with_annotations": 164
        },
        "error_count": 24,
        "isCompiled": false,
        "errors": [
            "merge_f40757.py:106: error: Missing return statement  [empty-body]",
            "merge_f40757.py:173: error: Missing return statement  [empty-body]",
            "merge_f40757.py:204: error: Missing return statement  [empty-body]",
            "merge_f40757.py:228: error: Missing return statement  [empty-body]",
            "merge_f40757.py:233: error: Missing return statement  [empty-body]",
            "merge_f40757.py:249: error: Missing return statement  [empty-body]",
            "merge_f40757.py:259: error: Missing return statement  [empty-body]",
            "merge_f40757.py:268: error: Missing return statement  [empty-body]",
            "merge_f40757.py:281: error: Missing return statement  [empty-body]",
            "merge_f40757.py:290: error: Missing return statement  [empty-body]",
            "merge_f40757.py:299: error: Missing return statement  [empty-body]",
            "merge_f40757.py:361: error: Missing return statement  [empty-body]",
            "merge_f40757.py:381: error: Missing return statement  [empty-body]",
            "merge_f40757.py:385: error: Missing return statement  [empty-body]",
            "merge_f40757.py:393: error: Missing return statement  [empty-body]",
            "merge_f40757.py:397: error: Missing return statement  [empty-body]",
            "merge_f40757.py:404: error: Missing return statement  [empty-body]",
            "merge_f40757.py:413: error: Missing return statement  [empty-body]",
            "merge_f40757.py:422: error: Missing return statement  [empty-body]",
            "merge_f40757.py:429: error: Missing return statement  [empty-body]",
            "merge_f40757.py:437: error: Missing return statement  [empty-body]",
            "merge_f40757.py:446: error: Missing return statement  [empty-body]",
            "merge_f40757.py:450: error: Missing return statement  [empty-body]",
            "merge_f40757.py:458: error: Missing return statement  [empty-body]",
            "Found 24 errors in 1 file (checked 1 source file)"
        ]
    },
    "message_6587fb.py": {
        "stats": {
            "total_parameters": 42,
            "parameters_with_annotations": 42
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "message_6587fb.py:405: error: Name \"func_j1e1b7l5\" is not defined  [name-defined]",
            "message_6587fb.py:431: error: Missing return statement  [return]",
            "message_6587fb.py:436: error: Name \"direct\" is not defined  [name-defined]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "message_send_b7048c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "message_send_b7048c.py:311: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "missing_3e0a9c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "missing_3e0a9c.py:403: error: EOF while scanning triple-quoted string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "namespace_67e527.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "namespace_67e527.py:336: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "object_array_68abb9.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "object_array_68abb9.py:406: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "packager_d0d7be.py": {
        "stats": {
            "total_parameters": 86,
            "parameters_with_annotations": 57
        },
        "error_count": 38,
        "isCompiled": false,
        "errors": [
            "packager_d0d7be.py:39: error: Name \"Package\" is not defined  [name-defined]",
            "packager_d0d7be.py:98: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_deployment_package_filename\"  [attr-defined]",
            "packager_d0d7be.py:101: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_get_requirements_filename\"  [attr-defined]",
            "packager_d0d7be.py:102: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_hash_project_dir\"  [attr-defined]",
            "packager_d0d7be.py:122: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_iter_app_filenames\"  [attr-defined]",
            "packager_d0d7be.py:135: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_iter_chalice_lib_if_needed\"  [attr-defined]",
            "packager_d0d7be.py:144: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_iter_app_filenames\"  [attr-defined]",
            "packager_d0d7be.py:150: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_hash_vendor_dir\"  [attr-defined]",
            "packager_d0d7be.py:171: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_needs_latest_version\"  [attr-defined]",
            "packager_d0d7be.py:175: error: \"BaseLambdaDeploymentPackager\" has no attribute \"_add_app_files\"  [attr-defined]",
            "packager_d0d7be.py:202: error: \"DependencyBuilder\" has no attribute \"build_site_packages\"  [attr-defined]",
            "packager_d0d7be.py:215: error: \"LambdaDeploymentPackager\" has no attribute \"deployment_package_filename\"  [attr-defined]",
            "packager_d0d7be.py:220: error: \"LambdaDeploymentPackager\" has no attribute \"_create_output_dir_if_needed\"  [attr-defined]",
            "packager_d0d7be.py:222: error: \"LambdaDeploymentPackager\" has no attribute \"_get_requirements_filename\"  [attr-defined]",
            "packager_d0d7be.py:224: error: \"LambdaDeploymentPackager\" has no attribute \"_build_python_dependencies\"  [attr-defined]",
            "packager_d0d7be.py:228: error: \"LambdaDeploymentPackager\" has no attribute \"_add_py_deps\"  [attr-defined]",
            "packager_d0d7be.py:229: error: \"LambdaDeploymentPackager\" has no attribute \"_add_app_files\"  [attr-defined]",
            "packager_d0d7be.py:230: error: \"LambdaDeploymentPackager\" has no attribute \"_add_vendor_files\"  [attr-defined]",
            "packager_d0d7be.py:241: error: \"AppOnlyDeploymentPackager\" has no attribute \"deployment_package_filename\"  [attr-defined]",
            "packager_d0d7be.py:246: error: \"AppOnlyDeploymentPackager\" has no attribute \"_create_output_dir_if_needed\"  [attr-defined]",
            "packager_d0d7be.py:249: error: \"AppOnlyDeploymentPackager\" has no attribute \"_add_app_files\"  [attr-defined]",
            "packager_d0d7be.py:253: error: \"AppOnlyDeploymentPackager\" has no attribute \"_deployment_package_filename\"  [attr-defined]",
            "packager_d0d7be.py:258: error: \"AppOnlyDeploymentPackager\" has no attribute \"_iter_app_filenames\"  [attr-defined]",
            "packager_d0d7be.py:277: error: \"LayerDeploymentPackager\" has no attribute \"deployment_package_filename\"  [attr-defined]",
            "packager_d0d7be.py:279: error: \"LayerDeploymentPackager\" has no attribute \"_create_output_dir_if_needed\"  [attr-defined]",
            "packager_d0d7be.py:285: error: \"LayerDeploymentPackager\" has no attribute \"_get_requirements_filename\"  [attr-defined]",
            "packager_d0d7be.py:287: error: \"LayerDeploymentPackager\" has no attribute \"_build_python_dependencies\"  [attr-defined]",
            "packager_d0d7be.py:292: error: \"LayerDeploymentPackager\" has no attribute \"_add_py_deps\"  [attr-defined]",
            "packager_d0d7be.py:293: error: \"LayerDeploymentPackager\" has no attribute \"_add_vendor_files\"  [attr-defined]",
            "packager_d0d7be.py:295: error: \"LayerDeploymentPackager\" has no attribute \"_check_valid_package\"  [attr-defined]",
            "packager_d0d7be.py:307: error: \"LayerDeploymentPackager\" has no attribute \"_deployment_package_filename\"  [attr-defined]",
            "packager_d0d7be.py:311: error: \"LayerDeploymentPackager\" has no attribute \"_get_requirements_filename\"  [attr-defined]",
            "packager_d0d7be.py:320: error: \"LayerDeploymentPackager\" has no attribute \"_hash_vendor_dir\"  [attr-defined]",
            "packager_d0d7be.py:339: error: Name \"PipRunner\" is not defined  [name-defined]",
            "packager_d0d7be.py:342: error: Name \"PipRunner\" is not defined  [name-defined]",
            "packager_d0d7be.py:342: error: Name \"SubprocessPip\" is not defined  [name-defined]",
            "packager_d0d7be.py:347: error: \"DependencyBuilder\" has no attribute \"_iter_all_compatibility_tags\"  [attr-defined]",
            "packager_d0d7be.py:349: error: \"DependencyBuilder\" has no attribute \"_is_compatible_platform_tag\"  [attr-defined]",
            "Found 38 errors in 1 file (checked 1 source file)"
        ]
    },
    "partial_619858.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "partial_619858.py:320: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "pretty_5d5a4b.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "pretty_5d5a4b.py:481: error: EOF while scanning triple-quoted string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "providers_d61054.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "providers_d61054.py:190: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "push_notifications_9b9efe.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "push_notifications_9b9efe.py:353: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "pytables_a9636c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "pytables_a9636c.py:450: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "range_eccc67.py": {
        "stats": {
            "total_parameters": 93,
            "parameters_with_annotations": 48
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "range_eccc67.py:61: error: Argument 2 to \"range\" has incompatible type \"Union[int, RangeIndex, None]\"; expected \"SupportsIndex\"  [arg-type]",
            "range_eccc67.py:362: error: Missing return statement  [return]",
            "range_eccc67.py:369: error: Name \"old\" is not defined  [name-defined]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "rate_limiter_5a146f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "rate_limiter_5a146f.py:424: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "rocketchat_52a9b8.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "rocketchat_52a9b8.py:83: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "routing_66b713.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "routing_66b713.py:386: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "run_b777ab.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_b777ab.py:419: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "sql_07b300.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "sql_07b300.py:41: error: closing parenthesis ')' does not match opening parenthesis '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "stata_4ae9e0.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "stata_4ae9e0.py:41: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "streams_748e41.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "streams_748e41.py:359: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "string__8c20b1.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "string__8c20b1.py:420: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "stripe_8fa3cb.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "stripe_8fa3cb.py:92: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "stubs_b63ee1.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "stubs_b63ee1.py:409: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "style_render_e06ec7.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "style_render_e06ec7.py:352: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "template_0e4e35.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "template_0e4e35.py:476: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_arrow_ebc6ab.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_arrow_ebc6ab.py:293: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_black_2d705a.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_black_2d705a.py:326: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_categorical_c93963.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_categorical_c93963.py:298: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_constructors_c6bb5c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_constructors_c6bb5c.py:346: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_context_0bb4b5.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_context_0bb4b5.py:370: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_core_9112bf.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_core_9112bf.py:355: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_datetime_index_0892c0.py": {
        "stats": {
            "total_parameters": 25,
            "parameters_with_annotations": 24
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_datetime_index_0892c0.py:84: error: \"Callable[[Any], Any]\" has no attribute \"index\"  [attr-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "test_gen_data_e67a06.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_gen_data_e67a06.py:289: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_internals_d33223.py": {
        "stats": {
            "total_parameters": 36,
            "parameters_with_annotations": 21
        },
        "error_count": 19,
        "isCompiled": false,
        "errors": [
            "test_internals_d33223.py:21: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]",
            "test_internals_d33223.py:30: error: Name \"create_mgr\" is not defined  [name-defined]",
            "test_internals_d33223.py:71: error: Argument 1 to \"len\" has incompatible type \"Union[Sequence[int], slice]\"; expected \"Sized\"  [arg-type]",
            "test_internals_d33223.py:151: error: Need type annotation for \"mgr_items\" (hint: \"mgr_items: List[<type>] = ...\")  [var-annotated]",
            "test_internals_d33223.py:152: error: Need type annotation for \"block_placements\" (hint: \"block_placements: Dict[<type>, <type>] = ...\")  [var-annotated]",
            "test_internals_d33223.py:159: error: Incompatible types in assignment (expression has type \"List[str]\", variable has type \"str\")  [assignment]",
            "test_internals_d33223.py:208: error: \"Callable[[], Any]\" has no attribute \"copy\"  [attr-defined]",
            "test_internals_d33223.py:213: error: \"Callable[[], Any]\" has no attribute \"copy\"  [attr-defined]",
            "test_internals_d33223.py:222: error: \"Callable[[], Any]\" has no attribute \"copy\"  [attr-defined]",
            "test_internals_d33223.py:233: error: \"Callable[[], Any]\" has no attribute \"copy\"  [attr-defined]",
            "test_internals_d33223.py:239: error: \"Callable[[], Any]\" has no attribute \"copy\"  [attr-defined]",
            "test_internals_d33223.py:290: error: \"Callable[[], Any]\" has no attribute \"_rebuild_blknos_and_blklocs\"  [attr-defined]",
            "test_internals_d33223.py:294: error: \"Callable[[], Any]\" has no attribute \"iget\"  [attr-defined]",
            "test_internals_d33223.py:328: error: \"Callable[[], Any]\" has no attribute \"iget\"  [attr-defined]",
            "test_internals_d33223.py:330: error: \"Callable[[], Any]\" has no attribute \"iget\"  [attr-defined]",
            "test_internals_d33223.py:332: error: \"Callable[[], Any]\" has no attribute \"iget\"  [attr-defined]",
            "test_internals_d33223.py:337: error: \"Callable[[], Any]\" has no attribute \"insert\"  [attr-defined]",
            "test_internals_d33223.py:338: error: \"Callable[[], Any]\" has no attribute \"iset\"  [attr-defined]",
            "test_internals_d33223.py:339: error: \"Callable[[], Any]\" has no attribute \"iget\"  [attr-defined]",
            "Found 19 errors in 1 file (checked 1 source file)"
        ]
    },
    "test_logging_b7910e.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_logging_b7910e.py:316: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_microbatch_124d73.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 11
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_microbatch_124d73.py:330: error: \"TestMicroBatchBoundsDefault\" has no attribute \"func_a86bxq7\"  [attr-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "test_plugins_493c2b.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_plugins_493c2b.py:294: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_readers_6fbe49.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_readers_6fbe49.py:145: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_s3_fad4be.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_s3_fad4be.py:346: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_selector_bbc47d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_selector_bbc47d.py:296: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_sparse_d759ae.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_sparse_d759ae.py:334: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_sql_f4958a.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_sql_f4958a.py:390: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_stata_db4b21.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_stata_db4b21.py:119: error: closing parenthesis ']' does not match opening parenthesis '(' on line 116  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_validation_2c8d12.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_validation_2c8d12.py:406: error: EOL while scanning string literal  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_wrap_modes_beed23.py": {
        "stats": {
            "total_parameters": 114,
            "parameters_with_annotations": 114
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_writers_3a0994.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_writers_3a0994.py:69: error: closing parenthesis ')' does not match opening parenthesis '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "token_network_5df8c5.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "token_network_5df8c5.py:370: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "trade_model_19dfec.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "trade_model_19dfec.py:131: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "wrappers_34ca66.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "wrappers_34ca66.py:431: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "_base_2ce4a7.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "_base_2ce4a7.py:41: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "_core_627b18.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "_core_627b18.py:402: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "_models_dd672f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "_models_dd672f.py:455: error: unexpected EOF while parsing  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    }
}